## COMP576 - Intro to Deep Learning
Jin Kwon (netid: jk14)

## Task One : Python Machine Learning Stack (Anaconda)
Below is the result of running `>> conda info` in terminal

jin (master) COMP576 $ conda info  
Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.18.4
       root environment : /Users/jin-hyukkwon/miniconda3  (writable)
    default environment : /Users/jin-hyukkwon/miniconda3
       envs directories : /Users/jin-hyukkwon/miniconda3/envs
                          /Users/jin-hyukkwon/.conda/envs
          package cache : /Users/jin-hyukkwon/miniconda3/pkgs
                          /Users/jin-hyukkwon/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/jin-hyukkwon/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.18.4 CPython/3.6.0 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20

## Task Two: Interactive Terminal (IPython)
I am writing this report on a Jupyter Notebook!

## Task Three: Transition from MATLAB to Python  


In [1]:
# load packages
from numpy import * 
import scipy.linalg
print('packages loaded!')

packages loaded!


#### 1. 

In [2]:
# load a random array a
a = array([3,4])
b = array([[1,2,3], [4,5,6]])
print('numpy functions from this point will be tested with the following \
        arrays: \n\n a = {}, \n b = {}'.format(a, b), '\n')
# get the number of dimensions of an array
print('ndim - a: {},  b: {}'.format(ndim(a), ndim(b)))
print('size - a: {},  b: {}'.format(size(a), size(b)))
print('shape - a: {},  b: {}'.format(shape(a), shape(b)))
n = 1
print('a.shape[n-1] - a: {},  b: {}'.format(a.shape[n-1], b.shape[n-1]))
n = 2
print('a.shape[n-1] - b: {}'.format(b.shape[n-1]))

numpy functions from this point will be tested with the following         arrays: 

 a = [3 4], 
 b = [[1 2 3]
 [4 5 6]] 

ndim - a: 1,  b: 2
size - a: 2,  b: 6
shape - a: (2,),  b: (2, 3)
a.shape[n-1] - a: 2,  b: 2
a.shape[n-1] - b: 3


#### 2.

In [3]:
a = array([[1., 2., 3.], [4., 5., 6.]])
b = array([['a', 'b', 'c'], ['d', 'e', 'f']])
c = array([[1.1, 2.2, 3.3], [4.4, 5.5, 6.6]])
d = array([[0, 0, 0], [0, 0, 0]])

aa = random.rand(10,10)
print(vstack([hstack([a,b]),hstack([c,d])]))
print(bmat('a b; c d').A)
print(aa[-1])
print(aa[1, 2])
print(aa[1], aa[1,:])
print(aa[0:2], aa[:2], aa[0:2, :])
print(aa[-1:])
print(aa[0:2][:,1:2])
print(aa[ 2:21:2, :])
print(aa[::2, :])
print(aa[::-1,:])
print(aa[r_[:len(a),0]])

[['1.0' '2.0' '3.0' 'a' 'b' 'c']
 ['4.0' '5.0' '6.0' 'd' 'e' 'f']
 ['1.1' '2.2' '3.3' '0.0' '0.0' '0.0']
 ['4.4' '5.5' '6.6' '0.0' '0.0' '0.0']]
[['1.0' '2.0' '3.0' 'a' 'b' 'c']
 ['4.0' '5.0' '6.0' 'd' 'e' 'f']
 ['1.1' '2.2' '3.3' '0.0' '0.0' '0.0']
 ['4.4' '5.5' '6.6' '0.0' '0.0' '0.0']]
[ 0.29267491  0.5619626   0.82840769  0.98555405  0.72581021  0.51604735
  0.55889312  0.44370334  0.87919938  0.13868008]
0.205663593317
[ 0.7586692   0.88017594  0.20566359  0.19107589  0.70473396  0.1836007
  0.75716246  0.32357388  0.09314595  0.6432259 ] [ 0.7586692   0.88017594  0.20566359  0.19107589  0.70473396  0.1836007
  0.75716246  0.32357388  0.09314595  0.6432259 ]
[[ 0.41024128  0.30789023  0.64341743  0.97876491  0.96930526  0.69297939
   0.12598782  0.11291529  0.60175615  0.01692587]
 [ 0.7586692   0.88017594  0.20566359  0.19107589  0.70473396  0.1836007
   0.75716246  0.32357388  0.09314595  0.6432259 ]] [[ 0.41024128  0.30789023  0.64341743  0.97876491  0.96930526  0.69297939
   0

#### 3. 

In [4]:
print(aa.transpose())
print(a.T)
print(a.conj().transpose())
print(a.conj().T)
print(a.dot(c.T))
print(a*c)
print(a/c)
print(a**3)

[[ 0.41024128  0.7586692   0.82134706  0.32996227  0.29265173  0.20696866
   0.71537908  0.03368528  0.26673991  0.29267491]
 [ 0.30789023  0.88017594  0.35851218  0.63525905  0.54396487  0.06394913
   0.39093018  0.89687987  0.44791666  0.5619626 ]
 [ 0.64341743  0.20566359  0.72657934  0.09158368  0.33027969  0.45960316
   0.63053527  0.42934602  0.16668434  0.82840769]
 [ 0.97876491  0.19107589  0.78219663  0.87645841  0.69232899  0.79409628
   0.60390066  0.57064833  0.8951994   0.98555405]
 [ 0.96930526  0.70473396  0.54277983  0.68166515  0.5559343   0.6134333
   0.71398408  0.70632112  0.81840665  0.72581021]
 [ 0.69297939  0.1836007   0.28596314  0.73496001  0.29408489  0.95608249
   0.03843323  0.55508259  0.69176248  0.51604735]
 [ 0.12598782  0.75716246  0.07208199  0.51455724  0.85447992  0.53434204
   0.46302199  0.06623165  0.60934893  0.55889312]
 [ 0.11291529  0.32357388  0.3626044   0.04274365  0.34814625  0.49400899
   0.25677319  0.04735976  0.76646665  0.44370334]
 

#### 4. Conditions

In [5]:
cc = array([[1,2,3],[4,5,6],[7,8,9]])
v = array([1,2,5])

(a>5)
nonzero(a>0.5)
a[:,nonzero(c>0.5)[0]]
print(len(cc), len(v))

cc[:, v.T>0.5]
c[c<5]=0
a*(a>0.5)

3 3


array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

#### 5. assigning, copying, 

In [6]:
c[:] = 3
y = c.copy()
y = c[1,:].copy()
y = c.flatten

#### 6. building types of vectors

In [7]:
arange(1., 11.)
r_[1.:11.]
r_[1:10:10j]

arange(10.)
r_[:10.]
r_[:9:10j]

arange(1.,11.)[:, newaxis]
zeros((3,4))
zeros((3,4,5))
ones((3,4))
eye(3)
diag(a)
diag(a,0)

array([ 1.,  5.])

#### 7.  And more..

In [41]:
import numpy as np
import scipy
from scipy import sparse
# import numpy.linalg.matrix_rank


a = array([[8,1,2], [1,10,6], [2,6,9]])
b = array([[1,1,3], [4,4,6], [7,8,9]])
c = array([[2,3,4],[5,6,7],[8,9,10]])

np.random.rand(3,4)
linspace(1,3,4)
mgrid[0:9., 0:6.]
meshgrid(r_[0:9.], r_[0:6.])
ogrid[0:9., 0:6.]
ix_(r_[0:9.], r_[0:6.])
meshgrid([1,2,4],[2,4,5])

m = 2
n = 3
tile(a, (m,n))
concatenate((a,b), 1)
hstack((a, b))
column_stack((a,b))

concatenate((a,b)) 
vstack((a,b)) 
a.max()
a.max(0)
a.max(1)
maximum(a, c)
sqrt(dot(v,v)) 
np.linalg.norm(v)

logical_and(a,b)
logical_or(a, b)
a & b
a | b
linalg.inv(a)
linalg.pinv(a)
np.linalg.matrix_rank(a)
linalg.solve(a,b)
linalg.lstsq(a,b)
U, S, Vh = linalg.svd(a)
V = Vh.T

d = array([[1,2],[3,4]])
linalg.cholesky(a).T
D,V = linalg.eig(a)
V,D = np.linalg.eig(b)
Q,R = scipy.linalg.qr(a)
P, L,U = scipy.linalg.lu(a) 
LU,P=scipy.linalg.lu_factor(a)
# np.fft(a)   
# ifft(a)
sort(a) 
a.sort()
I = argsort(a[:,2])
b=a[I,:]
linalg.lstsq(a,b)
# scipy.signal.resample(x, len(x)/q)
unique(a)
a.squeeze()

array([[ 1,  2,  8],
       [ 1,  6, 10],
       [ 2,  6,  9]])

## Task 4: Plotting (matPlotLib/PyPlot)

In [ ]:
import matplotlib.pyplot as plt
plt.plot([1,2,3,4], [1,2,7,14])
plt.axis([0,6,0,20])
plt.show()

## Task 5: Paste your VCS account into your report  
Link to GitHub: [github.com/jinkwon14](github.com/jinkwon14)

## Task 6: Integrated Development Environment (PyCharm)
Link to "project": 